modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="docmod" #mandatory
version="5.0" #mandatory
updateJSONURL="https://raw.githubusercontent.com/9e-Docteur/docteam-modupdater/main/docmod_updater.json"
displayName="DocMod 5.0" #mandatory
logoFile="docmod_logo.png" #optional
credits="PandaRebel4307, Josia, Killar.exe, Balisto91, Itsaykow, Robainks, Garatim" #optional
authors="9e_Docteur" #optional
description='''Mod Created By 9e_Docteur, Textures by 9e_Docteur and PandaRebel4307. Coded by 9e_Docteur, Killar.exe, and Josia. Tardis Exterior by Valox.'''
[[dependencies.docmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.docmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.1,1.19.2]"
    ordering="NONE"
    side="BOTH"
