modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="docmod" #mandatory
version="7.0" #mandatory
updateJSONURL="https://raw.githubusercontent.com/9e-Docteur/docmod/main/update.json"
displayName="DocMod" #mandatory
logoFile="docmod_logo.png" #optional
credits="PandaRebel4307, Josia, Killar.exe, Balisto91, Itsaykow, Robainks, Garatim" #optional
authors="9e_Docteur" #optional
description='''Mod Created By 9e_Docteur, Textures by 9e_Docteur, PandaRebel4307, stoneRed, and Plurscraft. Coded by 9e_Docteur, Killar.exe, and Josia. Tardis Exterior by Valox.'''
[[dependencies.docmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[45,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.docmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,]"
    ordering="NONE"
    side="BOTH"
